# Generated by Django 2.1.5 on 2019-08-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_car_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_img',
            new_name='pretty_picture',
        ),
    ]
